[project]
name = "crizit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.2",
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "tabulate>=0.9.0",
]
